/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream de eventos (Server-Sent Events)
         * @description Eventos: marco-disparado (dados no formato Marco) e jornada-atualizada (formato Jornada). Um comentário "ping" a cada 20 s mantém a conexão. Ao reconectar, busque GET /api/v1/jornadas/atual para recuperar os marcos pendentes.
         */
        get: operations["conectar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jornadas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inicia o dia. Encerra antes a jornada esquecida de um dia anterior, se houver.
         * @description Exige o perfil físico preenchido: sem ele, responde 409.
         */
        post: operations["iniciar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jornadas/atual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jornada aberta ou, sem ela, a de hoje */
        get: operations["atual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jornadas/{id}/finalizacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finaliza o dia. Repetir devolve a mesma situação. */
        post: operations["finalizar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jornadas/{id}/pausa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pausa a jornada (almoço). O tempo trabalhado congela. */
        post: operations["pausar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jornadas/{id}/retomada": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retoma a jornada pausada */
        post: operations["retomar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marcos/{id}/adiamento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adia o bloco de exercício. Repetir devolve a mesma situação.
         * @description O bloco seguinte passa a ter 10 min e decide o destino dos dois. Só vale uma vez por cadeia e nunca no último bloco do dia; a água não é adiada.
         */
        post: operations["adiar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marcos/{id}/conclusao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Conclui o marco. Repetir devolve a mesma situação. */
        post: operations["concluir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marcos/{id}/falha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marca falha no marco. Repetir devolve a mesma situação. */
        post: operations["falhar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marcos/{id}/recebimento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirma que o marco chegou à tela
         * @description Sem a confirmação, o prazo vencido vira NAO_ENTREGUE em vez de FALHA.
         */
        post: operations["confirmarRecebimento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil físico atual */
        get: operations["consultar"];
        /** Cria ou substitui o perfil físico. Vale para os próximos blocos. */
        put: operations["salvar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sistema/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Informa que o backend está no ar, com a versão e o horário do servidor */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Bloco de exercício do marco, como foi proposto no disparo. */
        Bloco: {
            /** @description Se o bloco compensa o anterior, que foi adiado; nesse caso tem 10 min */
            compensaAdiamento: boolean;
            /**
             * Format: int32
             * @description Duração do bloco: 5 ou 10 min
             * @example 5
             */
            duracaoMin: number;
            /** @description Exercícios na ordem em que devem ser feitos */
            itens: components["schemas"]["ItemDoBloco"][];
            /**
             * Format: int64
             * @description Soma das estimativas dos exercícios, com as trocas
             * @example 278
             */
            segundosEstimados: number;
        };
        IniciarJornada: {
            /**
             * Format: int32
             * @description Duração dos blocos de exercício do dia, em minutos: 5 ou 10. Sem ela, 5 min.
             * @default 5
             * @example 5
             */
            duracaoBlocoMin: number;
            /**
             * Format: int32
             * @description Meta de água do dia, em ml. Sem ela, 3.000 ml.
             * @default 3000
             * @example 3000
             */
            metaAguaMl: number;
        };
        ItemDoBloco: {
            /** @example Sentar e levantar da cadeira */
            exercicio: string;
            /** @example Pernas */
            grupo: string;
            /** @example Sente e levante da cadeira sem usar as mãos, com os pés na largura do quadril. */
            instrucao: string;
            /**
             * @description "10 repetições", "6 por lado" ou "20 s"
             * @example 10 repetições
             */
            quantidade: string;
        };
        /** @description Situação da jornada no instante calculadoEm. Horários no fuso America/Sao_Paulo. */
        Jornada: {
            /**
             * @description Soma dos marcos de hidratação concluídos
             * @example 562.5
             */
            aguaIngeridaMl: number;
            /** Format: date-time */
            calculadoEm: string;
            /**
             * Format: date
             * @description Dia em que a jornada começou
             */
            dataReferencia: string;
            /**
             * Format: int32
             * @description Duração dos blocos de exercício escolhida ao iniciar o dia. O bloco que compensa um adiamento tem 10 min.
             * @example 5
             */
            duracaoBlocoMin: number;
            /** Format: date-time */
            finalizadaEm: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            iniciadaEm: string;
            /** @description Água e exercício em ordem de horário; na hora cheia, a água vem antes */
            marcos: components["schemas"]["Marco"][];
            /**
             * Format: int32
             * @example 3000
             */
            metaAguaMl: number;
            /**
             * Format: date-time
             * @description Início da pausa em curso; nulo fora da pausa
             */
            pausadaDesde: string | null;
            /** @enum {string} */
            status: "EM_ANDAMENTO" | "PAUSADA" | "FINALIZADA" | "ENCERRADA_AUTOMATICAMENTE";
            /**
             * Format: int64
             * @description Tempo trabalhado até calculadoEm, sem as pausas. Enquanto a jornada estiver em andamento, a tela soma o tempo decorrido desde então.
             * @example 5400
             */
            tempoTrabalhadoSegundos: number;
        };
        /** @description Lembrete da jornada. Horários no fuso America/Sao_Paulo. */
        Marco: {
            /** @description Bloco de exercício. Nulo na água e no exercício que ainda não disparou. */
            bloco: components["schemas"]["Bloco"] | null;
            /** @enum {string} */
            categoria: "HIDRATACAO" | "EXERCICIO";
            /** Format: date-time */
            disparadoEm: string | null;
            /** Format: uuid */
            id: string;
            /** @example Beba ~190 ml. Levante-se para buscar a água. */
            mensagem: string;
            /** @description Se o botão Adiar vale agora: só no exercício pendente que não compensa um adiamento e não é o último do dia */
            podeAdiar: boolean;
            /** Format: date-time */
            recebidoEm: string | null;
            /** Format: date-time */
            respondidoEm: string | null;
            /**
             * Format: int64
             * @description Tempo trabalhado em que o marco dispara
             * @example 1800
             */
            segundosTrabalhadosPrevistos: number;
            /**
             * Format: int32
             * @description Ordem do marco na categoria, a partir de 1
             * @example 1
             */
            sequencia: number;
            /** @enum {string} */
            status: "AGENDADO" | "PENDENTE" | "CONCLUIDO" | "FALHA" | "NAO_ENTREGUE" | "NAO_CONCLUIDO" | "ADIADO";
            /**
             * Format: int32
             * @description Volume para exibir, arredondado para a dezena. Nulo no exercício.
             * @example 190
             */
            volumeAproximadoMl: number | null;
            /**
             * @description Volume exato: meta ÷ 16. Nulo no exercício.
             * @example 187.5
             */
            volumeMl: number | null;
        };
        /** @description Perfil físico do usuário. Vale para os blocos montados depois da última alteração. */
        Perfil: {
            aceitaChao: boolean;
            articulacoesPoupadas: ("JOELHO" | "OMBRO" | "PUNHO" | "LOMBAR" | "CERVICAL")[];
            equipamentos: ("APOIO_DE_FLEXAO" | "HALTERES_2KG")[];
            /** @enum {string} */
            nivel: "INICIANTE" | "INTERMEDIARIO";
        };
        ProblemDetail: {
            detail?: string;
            /** Format: uri */
            instance?: string;
            properties?: {
                [key: string]: unknown;
            };
            /** Format: int32 */
            status?: number;
            title?: string;
            /** Format: uri */
            type?: string;
        };
        SalvarPerfil: {
            /** @description Se exercícios deitado ou de quatro podem entrar no bloco */
            aceitaChao: boolean;
            /** @description Articulações a poupar. Vazio ou ausente: nenhuma. */
            articulacoesPoupadas?: ("JOELHO" | "OMBRO" | "PUNHO" | "LOMBAR" | "CERVICAL")[];
            /** @description Equipamentos disponíveis. Cadeira e mesa já contam como disponíveis. */
            equipamentos?: ("APOIO_DE_FLEXAO" | "HALTERES_2KG")[];
            /** @enum {string} */
            nivel: "INICIANTE" | "INTERMEDIARIO";
        };
        /** @description Situação do backend. Não consulta o banco; o estado do banco fica em /actuator/health. */
        StatusResposta: {
            /**
             * Format: date-time
             * @description Horário do servidor no fuso de negócio
             * @example 2026-10-01T09:00:00-03:00
             */
            agora: string;
            /** @example pausa-ativa */
            aplicacao: string;
            /** @example America/Sao_Paulo */
            fuso: string;
            /** @example 0.2.0 */
            versao: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    conectar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conexão aberta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    iniciar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IniciarJornada"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jornada"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    atual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Há jornada aberta ou de hoje */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jornada"];
                };
            };
            /** @description Nenhuma jornada hoje */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    finalizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jornada"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    pausar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jornada"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    retomar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jornada"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    adiar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jornada"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    concluir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jornada"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    falhar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jornada"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    confirmarRecebimento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    consultar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil preenchido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Perfil"];
                };
            };
            /** @description Perfil ainda não preenchido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    salvar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalvarPerfil"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Perfil"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResposta"];
                };
            };
        };
    };
}
